### ISSUE TITLE
Add Share button to the program events table

### ISSUE THREAD

**Issue by dylanedwardmoore** [empower-lab-dartmouth/care-insights#18]
It should appear in a new a column here
<img width="1135" alt="Screenshot 2024-07-11 at 8 46 36 AM" src="https://github.com/empower-lab-dartmouth/care-insights/assets/5395091/436af9f1-71fb-4d79-8833-e5a117cede4d">

**Comment by pape98** [comment]
@dylanedwardmoore Done!
