### ISSUE TITLE
Make editing and displaying info on the Snapshot work with a markdown rich text editor

### ISSUE THREAD

**Issue by dylanedwardmoore** [empower-lab-dartmouth/care-insights#19]
We should be able to display this view
<img width="1124" alt="Screenshot 2024-07-11 at 8 48 03 AM" src="https://github.com/empower-lab-dartmouth/care-insights/assets/5395091/9a0bc2dd-c801-4cec-910f-a5a260955a8c">
Editable as rich text like this page:
<img width="1138" alt="Screenshot 2024-07-11 at 8 49 30 AM" src="https://github.com/empower-lab-dartmouth/care-insights/assets/5395091/cdbc05cf-21dc-4e4b-8168-3ab68b0a26c6">

I'm not a huge fan of the editor I'm using right now on the ask me more page, so feel free to use a different one.

**Comment by pape98** [comment]
<img width="877" alt="Screenshot 2024-07-22 at 12 24 20 PM" src="https://github.com/user-attachments/assets/cbf574c3-4878-4b8e-998d-3958683240ff">
