### ISSUE TITLE
Rich text editor is broken on tell me more page

### ISSUE THREAD

**Issue by dylanedwardmoore** [empower-lab-dartmouth/care-insights#20]
Right now the link editor overflows in a weird way. 
<img width="1343" alt="Screenshot 2024-07-11 at 8 51 26 AM" src="https://github.com/empower-lab-dartmouth/care-insights/assets/5395091/82a2448e-a90f-49ac-80f2-11b61716f0b6">

Might be a simple fix

**Comment by pape98** [comment]
<img width="485" alt="Screenshot 2024-07-22 at 12 08 27 PM" src="https://github.com/user-attachments/assets/50d46688-69a6-4701-b944-25edb4b1509d">
