### ISSUE TITLE
The caregiver profile icon should show the first letter of the email, not "M"

### ISSUE THREAD

**Issue by dylanedwardmoore** [empower-lab-dartmouth/care-insights#24]
<img width="263" alt="Screenshot 2024-07-11 at 10 19 39 AM" src="https://github.com/empower-lab-dartmouth/care-insights/assets/5395091/203a4c6f-5260-453b-8ebe-98c46750ac6f">

**Comment by pape98** [comment]
@dylanedwardmoore done!
